# A script to load appropriate libraries and settings.
# Load in libraries

library( ggplot2 )
library( plotly )
library( peakPick )
library( signal )
library( smoother )
library( pdist )
library( abind )
library( wavelets )
library( FNN )
library( zoo )
library( deSolve )
library( fields )
library( grid )
library( gridExtra )
library( R.matlab )
#library( sn )
library( lhs )
library( lattice )
library( moments )
library( mvtnorm )
library( mclust )
library( MASS )
library( latex2exp )
library( ggpubr )
# Load Data
options(digits = 15)
options(digits.secs=3)

source( "FourierSourceFunctions.R" )
source( "WaveSplitSourceFunctions.R" )
source( "PeakExtractionSourceFunctions.R" )
source( 'EmulationSourceCode.R' )
source( 'BayesLinearDynamicUpdateSourceCode.R' )
source( 'DiscreteAnalysisSourceFunctions.R' )
source( 'ASWFSourceFunctions.R' )
source( 'AccessandLoadingDataSourceFunctions.R' )
source( 'mitdbSourceFunctions.R' )
source( 'AFDetectionSourceFunctions.R')
source( 'ECGSimulatorSourceFunctions.R')
source( 'HistoryMatchingSourceFunctions.R')
source( 'PlottingSourceFunctions.R' )
source( 'VectorisedOperationsSourceFunctions.R' )
source( 'DenistyFunctionsSourceFunctions.R' )
source( 'DenistyFunctionsSourceFunctions.R' )
source( 'BayesClassifierSourceFunctions.R' )
source( 'KernelDensityEstimationSourceFunctions.R')
print('Libraries, data options and source functions loaded.')

